[project]
name = "todoist-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "mcp[cli]>=1.9.0",
    "pydantic>=2.11.4",
    "todoist-api-python>=3.1.0",
]
